### ISSUE TITLE
eventhandler: log in goroutine after test has completed

### ISSUE THREAD

**Issue by nkryuchkov** [ssvlabs/ssv#1619]
https://github.com/ssvlabs/ssv/actions/runs/10367473608/job/28701306026

Might be related to https://github.com/ssvlabs/ssv/issues/1585

```
coverage: 10.2% of statements
panic: Log in goroutine after TestHandleBlockEventsStream has completed: 2024-08-13T10:43:14.873Z	INFO	execution_client	reconnecting	{"address": "ws://127.0.0.1:33945"}

goroutine 140 [running]:
testing.(*common).logDepth(0xc000449040, {0xc007298480, 0x5f}, 0x3)
	/opt/hostedtoolcache/go/1.22.5/x64/src/testing/testing.go:1028 +0x6d4
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.22.5/x64/src/testing/testing.go:1010
testing.(*common).Logf(0xc000449040, {0x30870a6, 0x2}, {0xc0060f81a0, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.22.5/x64/src/testing/testing.go:1061 +0xa5
go.uber.org/zap/zaptest.TestingWriter.Write({{0x3a51810?, 0xc000449040?}, 0x0?}, {0xc0003fac00, 0x60, 0x400})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zaptest/logger.go:146 +0x11e
go.uber.org/zap/zapcore.(*ioCore).Write(0xc00a026f30, {0x0, {0xc1a6ec10b410bdf4, 0x179da7f18, 0x4c634c0}, {0x309e786, 0x10}, {0x30976ea, 0xc}, {0x0, ...}, ...}, ...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/core.go:99 +0x193
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000990d00, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:253 +0x1f0
go.uber.org/zap.(*Logger).Info(0xc008f57d80, {0x30976ea, 0xc}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:247 +0x65
github.com/ssvlabs/ssv/eth/executionclient.(*ExecutionClient).reconnect.func1(0x77359400)
	/home/runner/work/ssv/ssv/eth/executionclient/execution_client.go:336 +0x7f
github.com/ssvlabs/ssv/utils/tasks.ExecWithInterval(0xc008cc7d80, 0x3b9aca00, 0xf224d4a00)
	/home/runner/work/ssv/ssv/utils/tasks/exec_interval.go:18 +0x4e
github.com/ssvlabs/ssv/eth/executionclient.(*ExecutionClient).reconnect(0xc0083b4a00, {0x3a49948, 0xc00027a320})
	/home/runner/work/ssv/ssv/eth/executionclient/execution_client.go:335 +0x348
github.com/ssvlabs/ssv/eth/executionclient.(*ExecutionClient).StreamLogs.func1()
	/home/runner/work/ssv/ssv/eth/executionclient/execution_client.go:[21](https://github.com/ssvlabs/ssv/actions/runs/10367473608/job/28701306026#step:5:22)3 +0x170
created by github.com/ssvlabs/ssv/eth/executionclient.(*ExecutionClient).StreamLogs in goroutine 112
	/home/runner/work/ssv/ssv/eth/executionclient/execution_client.go:181 +0x1a5
FAIL	github.com/ssvlabs/ssv/eth/eventhandler	6.364s
```

**Comment by nkryuchkov** [comment]
It should be fixed by https://github.com/ssvlabs/ssv/pull/1630
